version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: tinder_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tinder
    ports:
      - "5434:5432" # Меняем порт на 5434
    volumes:
      - tinder_postgres_data:/var/lib/postgresql/data

volumes:
  tinder_postgres_data:
